### PR TITLE
Fix unknown closure reason

### LINKED ISSUE #797: Fetch Circuit breaker pausing and display orderly in UI
Synthetixs circuit breaker (https://sips.synthetix.io/sips/sip-231/) at times of high volatility might pause markets. Currently our UI shows a cryptic message for users, which should be catched and shown as a simple "Markets are temporarily paused" or similar. 

See screenshot of a paused market mid-week:

Screen Shot 2022-05-05 at 13 21 31

## Deliverables
- Show message on Chart
- Show shortened message on badge in Position Card
- Same with FuturesMarketsTable
- Same with dropdown
- Check other places it might be visible

### PR DESCRIPTION
**Pull request by brossetti1**
fixing unknown state of market closure - returning `unknown` string for en.json reference vs null.

## Description
last week a market was temporarily paused for a reason unknown to us. we should have a default statement on a closed market if we do not know the reason why it was closed.

this was probably reasonCode 231 (see latency breaker actions in dune dashboard)
https://dune.com/joeyb/Synth-closures

here are the current [reason codes](https://github.com/Synthetixio/synthetix/blob/2a3640429acc07b6f485cde319fe742c921ee11e/index.js#L603-L617)

this issue is a result of [231 being 5 days ago](https://github.com/Synthetixio/synthetix/pull/1765) and the fact that we did not have a default status for unknown reason codes - resolved by adding both 231 in circuit breaker codes and adding `unknown` as the base default for reasons.

## Related issue
https://github.com/Synthetixio/synthetix/blob/e6b6aa3340ffc2536c814290e360190cc53f7a92/contracts/interfaces/ISystemStatus.sol#L13

closes #797 

## Motivation and Context
fix display of market pauses

## How Has This Been Tested?
locally

in order to reproduce on the test deploy, we need to get synthetix to update a market on kovan with reasonCode 231

## Screenshots (if appropriate):
Screen Shot 2022-05-08 at 8 51 50 PM
Screen Shot 2022-05-08 at 8 51 38 PM

## from kovan test code 231
Screen Shot 2022-05-09 at 9 17 14 AM
Screen Shot 2022-05-09 at 9 17 21 AM

### CODE REVIEW

**Comment by platschi** [comment]
Thanks for already catching this :) This was already assigned to you for this week (#797)

File: queries/futures/utils.ts [hunk 1]
```diff
@@ -238,11 +240,13 @@ export const getReasonFromCode = (reasonCode?: BigNumber): MarketClosureReason |
 		case 3:
 		case 55:
 		case 65:
+		case 231:
 			return 'circuit-breaker';
 		case 99999:
 			return 'emergency';
 		default:
-			return null;
+			console.log(Number(reasonCode));
```
Comment (LeifuChen) [inline queries/futures/utils.ts:248]: Shall we remove this `console.log` before merging?

**Review by LeifuChen — CHANGES_REQUESTED** [review]
@brossetti1 Good job! Just request a minor code clean before merging. Thanks.

File: queries/futures/utils.ts (hunk 1 above)
Comment (brossetti1) [reply queries/futures/utils.ts]: done

**Review by LeifuChen — APPROVED** [review]
Looks good to me.
