### PR TITLE
fix: connected network state color.

### LINKED ISSUE #561: Fix connected network state color
### Subject of the issue
Currently, when a wallet is connected to L2 Optimism, the wallet address is accompanied by a golden circle on L2, and a green circle on L1.

For consistency, the green circle should always be shown regardless of the network.

### Current design
Screen Shot 2022-03-30 at 11 24 10

### Desired design
Screen Shot 2022-03-30 at 11 19 55

### Deliverables
- Show a primary green `#7FD482` circle on the "connected wallet" state, regardless of the network the user is connected to.

### Reward 
25 SNX

### PR DESCRIPTION
**Pull request by zhyd1997**
## Related issue

Fixes #561 

## Screenshots (if appropriate):
L2 network state color

### CODE REVIEW

File: sections/shared/Layout/AppLayout/Header/ConnectionDot.tsx [hunk 1]
```diff
@@ -27,6 +27,9 @@ const ConnectionDot: React.FC<ConnectionDotProps> = (props) => {
 			case NetworkIdByName.goerli:
 				background = theme.colors.goerli;
 				break;
+			case NetworkIdByName['mainnet-ovm']:
+				background = theme.colors.optimism;
+				break;
```
Comment (zhyd1997) [inline sections/shared/Layout/AppLayout/Header/ConnectionDot.tsx:32]:
```js
// `network` value when switched to L2
{
    "id": 10,
    "name": "optimism",
    "useOvm": true
}
```

**Review by platschi — APPROVED** [review]
Works!

**Review by brossetti1 — APPROVED** [review]
