### PR TITLE
Fix UI issues on close modal position 

### LINKED ISSUE #495: Close Position Modal Improvements
### Subject of the issue
The Close Position Modal uses an outdated golden PrimaryButton. It should update to match the button with other modals (primarily the Open/Modify Position modal).

Additionally, the synth symbol is currently shown in front of an amount, without a space between the synth symbol and amount. 

Screen Shot 2022-03-28 at 15 44 38

### Deliverables

- [ ] Update golden "Close Position" button to match design. See "Confirm Order" modal for the correct button layout.
- [ ] Move synth symbol (e.g. ETH) behind the amount, leave a white space between amount and symbol 

### Rewards
25 SNX

### PR DESCRIPTION
**Pull request by benjabuidl**
## Description

- Updated height on close button to match other gold buttons. 
- Removed "s" from synth symbol and moved after number on size row. 

## Related issue
closes #495

## Motivation and Context
Fixes small UI issues with close position modal

## How Has This Been Tested?
Tested visually after created position for BTC and ETH. 

## Screenshots (if appropriate):
closepositionmodal
close_btc

### CODE REVIEW

File: sections/futures/PositionCard/ClosePositionModal.tsx [hunk 1]
```diff
@@ -108,7 +108,9 @@ const ClosePositionModal: FC<ClosePositionModalProps> = ({
 			},
 			{
 				label: t('futures.market.user.position.modal-close.size'),
-				value: formatCurrency(currencyKey, position?.size ?? zeroBN, { currencyKey }),
+				value: formatCurrency(currencyKey || '', position?.size ?? zeroBN, {
+					sign: currencyKey[0] === 's' ? currencyKey.slice(1) : currencyKey,
```
Comment (LeifuChen) [inline sections/futures/PositionCard/ClosePositionModal.tsx:112]: It works, but you may use the method in [currencies.ts](https://github.com/Kwenta/kwenta/blob/v2-dev/utils/currencies.ts#L13-L14), so it's easier to refactor the code in the future.

Comment (benjabuidl) [reply sections/futures/PositionCard/ClosePositionModal.tsx]: Hey @LeifuChen I updated this now. Thanks.

**Review by LeifuChen — APPROVED** [review]
Looks great. Thanks.
